options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # 1️⃣ Construir la imagen de Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--platform=linux/amd64',
      '-t', 'europe-west1-docker.pkg.dev/fastdiet/fastdiet-repo/fastdiet-backend:latest',
      '.'
    ]

  # 2️⃣ Subir la imagen al Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'europe-west1-docker.pkg.dev/fastdiet/fastdiet-repo/fastdiet-backend:latest'
    ]

  # 3️⃣ Ejecutar migraciones Alembic
  # Este paso ahora es correcto. No tiene el bloque 'secretManager' dentro.
  # Las variables como $$INSTANCE_CONNECTION_NAME se sustituirán automáticamente
  # por los valores definidos en el bloque 'availableSecrets' de abajo.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Run Migrations' # Es una buena práctica darle un ID al paso
    entrypoint: /bin/sh
    args:
      - -c
      - |
        echo "✅ Iniciando el paso de migración de la base de datos..."
        wget https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.8.2/cloud-sql-proxy.linux.amd64 -O /cloud_sql_proxy
        chmod +x /cloud_sql_proxy

        echo "   - Conectando a la instancia de Cloud SQL..."
        /cloud_sql_proxy --address 0.0.0.0 --port 5432 $$INSTANCE_CONNECTION_NAME &
        
        sleep 5

        echo "   - Ejecutando 'alembic upgrade head'..."
        docker run --network cloudbuild \
          -e DB_USER=$$DB_USER \
          -e DB_PASS=$$DB_PASS \
          -e DB_NAME=$$DB_NAME \
          -e DB_HOST=172.17.0.1 \
          -e DB_PORT=5432 \
          europe-west1-docker.pkg.dev/fastdiet/fastdiet-repo/fastdiet-backend:latest \
          alembic upgrade head
        echo "✅ Migración completada con éxito."

  # 4️⃣ Desplegar en Cloud Run
  # Este paso no cambia, ya estaba correcto.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fastdiet-backend-service'
      - '--image=europe-west1-docker.pkg.dev/fastdiet/fastdiet-repo/fastdiet-backend:latest'
      - '--platform=managed'
      - '--region=europe-west1'
      - '--allow-unauthenticated'
      - '--service-account=fastdiet-service-account@fastdiet.iam.gserviceaccount.com'
      - '--add-cloudsql-instances=fastdiet:europe-west1:fastdiet-db-instance'
      - '--set-secrets=INSTANCE_CONNECTION_NAME=INSTANCE_CONNECTION_NAME:latest'
      - '--set-secrets=DB_USER=DB_USER:latest'
      - '--set-secrets=DB_PASS=DB_PASS:latest'
      - '--set-secrets=DB_NAME=DB_NAME:latest'
      - '--set-secrets=JWT_SECRET_KEY=JWT_SECRET_KEY:latest'
      - '--set-secrets=JWT_ALGORITHM=JWT_ALGORITHM:latest'
      - '--set-secrets=SENDER_EMAIL=SENDER_EMAIL:latest'
      - '--set-secrets=BREVO_API_KEY=BREVO_API_KEY:latest'
      - '--set-secrets=WEB_CLIENT_ID=WEB_CLIENT_ID:latest'
      - '--set-secrets=SPOONACULAR_API_KEY=SPOONACULAR_API_KEY:latest'
      - '--set-secrets=GCS_BUCKET_NAME=GCS_BUCKET_NAME:latest'
      - '--set-secrets=CORS_ORIGINS=CORS_ORIGINS:latest'
      - '--set-secrets=TASK_SECRET_KEY=TASK_SECRET_KEY:latest'
      - '--set-secrets=GCP_PROJECT_ID=GCP_PROJECT_ID:latest'

# Opcional: especificar las imágenes creadas
images:
  - 'europe-west1-docker.pkg.dev/fastdiet/fastdiet-repo/fastdiet-backend:latest'

# --- BLOQUE CORRECTO PARA DEFINIR SECRETOS ---
# Este bloque debe estar al nivel superior del archivo (misma indentación que 'steps').
# Hace que los secretos estén disponibles para todos los pasos de la compilación.
availableSecrets:
  secretManager:
    - versionName: projects/fastdiet/secrets/INSTANCE_CONNECTION_NAME/versions/latest
      env: 'INSTANCE_CONNECTION_NAME'
    - versionName: projects/fastdiet/secrets/DB_USER/versions/latest
      env: 'DB_USER'
    - versionName: projects/fastdiet/secrets/DB_PASS/versions/latest
      env: 'DB_PASS'
    - versionName: projects/fastdiet/secrets/DB_NAME/versions/latest
      env: 'DB_NAME'