options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1️⃣ Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--platform=linux/amd64',
      '-t', 'europe-west1-docker.pkg.dev/fastdiet/fastdiet-repo/fastdiet-backend:latest',
      '.'
    ]

  # 2️⃣ Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'europe-west1-docker.pkg.dev/fastdiet/fastdiet-repo/fastdiet-backend:latest'
    ]

  # 3️⃣ Run Alembic migrations
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Run Migrations'
    secretEnv: ['INSTANCE_CONNECTION_NAME', 'DB_USER', 'DB_PASS', 'DB_NAME']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "✅ Initiating database migration step..."
        
        # Descargar cloud-sql-proxy
        curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.8.2/cloud-sql-proxy.linux.amd64
        chmod +x cloud-sql-proxy
        
        echo "   - Starting Cloud SQL Proxy..."
        ./cloud-sql-proxy --address 0.0.0.0 --port 3306 $$INSTANCE_CONNECTION_NAME &
        PROXY_PID=$$!
        
        echo "   - Waiting for proxy to be ready..."
        sleep 10
        
        echo "   - Running Alembic migrations..."
        docker run --network=host \
          -e DB_USER=$$DB_USER \
          -e DB_PASS=$$DB_PASS \
          -e DB_NAME=$$DB_NAME \
          -e DB_HOST=127.0.0.1 \
          -e DB_PORT=3306 \
          europe-west1-docker.pkg.dev/fastdiet/fastdiet-repo/fastdiet-backend:latest \
          alembic upgrade head
        
        MIGRATION_EXIT_CODE=$$?
        
        echo "   - Stopping Cloud SQL Proxy..."
        kill $$PROXY_PID
        
        if [ $$MIGRATION_EXIT_CODE -eq 0 ]; then
          echo "✅ Migration completed successfully."
        else
          echo "❌ Migration failed with exit code $$MIGRATION_EXIT_CODE"
          exit $$MIGRATION_EXIT_CODE
        fi

  # 4️⃣ Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fastdiet-backend-service'
      - '--image=europe-west1-docker.pkg.dev/fastdiet/fastdiet-repo/fastdiet-backend:latest'
      - '--platform=managed'
      - '--region=europe-west1'
      - '--allow-unauthenticated'
      - '--service-account=fastdiet-service-account@fastdiet.iam.gserviceaccount.com'
      - '--add-cloudsql-instances=fastdiet:europe-west1:fastdiet-db-instance'
      - '--set-secrets=INSTANCE_CONNECTION_NAME=INSTANCE_CONNECTION_NAME:latest'
      - '--set-secrets=DB_USER=DB_USER:latest'
      - '--set-secrets=DB_PASS=DB_PASS:latest'
      - '--set-secrets=DB_NAME=DB_NAME:latest'
      - '--set-secrets=JWT_SECRET_KEY=JWT_SECRET_KEY:latest'
      - '--set-secrets=JWT_ALGORITHM=JWT_ALGORITHM:latest'
      - '--set-secrets=SENDER_EMAIL=SENDER_EMAIL:latest'
      - '--set-secrets=BREVO_API_KEY=BREVO_API_KEY:latest'
      - '--set-secrets=WEB_CLIENT_ID=WEB_CLIENT_ID:latest'
      - '--set-secrets=SPOONACULAR_API_KEY=SPOONACULAR_API_KEY:latest'
      - '--set-secrets=GCS_BUCKET_NAME=GCS_BUCKET_NAME:latest'
      - '--set-secrets=CORS_ORIGINS=CORS_ORIGINS:latest'
      - '--set-secrets=TASK_SECRET_KEY=TASK_SECRET_KEY:latest'
      - '--set-secrets=GCP_PROJECT_ID=GCP_PROJECT_ID:latest'

images:
  - 'europe-west1-docker.pkg.dev/fastdiet/fastdiet-repo/fastdiet-backend:latest'

availableSecrets:
  secretManager:
    - versionName: projects/fastdiet/secrets/INSTANCE_CONNECTION_NAME/versions/latest
      env: 'INSTANCE_CONNECTION_NAME'
    - versionName: projects/fastdiet/secrets/DB_USER/versions/latest
      env: 'DB_USER'
    - versionName: projects/fastdiet/secrets/DB_PASS/versions/latest
      env: 'DB_PASS'
    - versionName: projects/fastdiet/secrets/DB_NAME/versions/latest
      env: 'DB_NAME'