options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Image'
    args: [
      'build',
      '--platform=linux/amd64',
      '-t', 'europe-west1-docker.pkg.dev/fastdiet/fastdiet-repo/fastdiet-backend:latest',
      '.'
    ]

  # 2. Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Image' # ID añadido aquí
    args: [
      'push',
      'europe-west1-docker.pkg.dev/fastdiet/fastdiet-repo/fastdiet-backend:latest'
    ]
    waitFor:
      - 'Build Image'

   # 3. Run migrations using Cloud SQL Proxy as sidecar
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Run Migrations'
    secretEnv: ['INSTANCE_CONNECTION_NAME', 'DB_USER', 'DB_PASS', 'DB_NAME']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
        chmod +x cloud_sql_proxy
        
        ./cloud_sql_proxy -instances=$$INSTANCE_CONNECTION_NAME=tcp:3306 &
        PROXY_PID=$!
        
        # Esperar a que el proxy esté listo
        echo "Waiting for Cloud SQL Proxy to be ready..."
        sleep 10
        
        docker run --rm \
          --network="host" \
          -e DB_HOST=127.0.0.1 \
          -e DB_PORT=3306 \
          -e DB_USER=$$DB_USER \
          -e DB_PASS=$$DB_PASS \
          -e DB_NAME=$$DB_NAME \
          europe-west1-docker.pkg.dev/fastdiet/fastdiet-repo/fastdiet-backend:latest \
          alembic upgrade head
        
        MIGRATION_RESULT=$?
        
        kill $PROXY_PID
        
        exit $MIGRATION_RESULT
    waitFor:
      - 'Push Image'

  # 4️⃣ Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fastdiet-backend-service'
      - '--image=europe-west1-docker.pkg.dev/fastdiet/fastdiet-repo/fastdiet-backend:latest'
      - '--platform=managed'
      - '--region=europe-west1'
      - '--allow-unauthenticated'
      - '--service-account=fastdiet-service-account@fastdiet.iam.gserviceaccount.com'
      - '--add-cloudsql-instances=fastdiet:europe-west1:fastdiet-db-instance'
      - '--set-secrets=INSTANCE_CONNECTION_NAME=INSTANCE_CONNECTION_NAME:latest'
      - '--set-secrets=DB_USER=DB_USER:latest'
      - '--set-secrets=DB_PASS=DB_PASS:latest'
      - '--set-secrets=DB_NAME=DB_NAME:latest'
      - '--set-secrets=JWT_SECRET_KEY=JWT_SECRET_KEY:latest'
      - '--set-secrets=JWT_ALGORITHM=JWT_ALGORITHM:latest'
      - '--set-secrets=SENDER_EMAIL=SENDER_EMAIL:latest'
      - '--set-secrets=BREVO_API_KEY=BREVO_API_KEY:latest'
      - '--set-secrets=WEB_CLIENT_ID=WEB_CLIENT_ID:latest'
      - '--set-secrets=SPOONACULAR_API_KEY=SPOONACULAR_API_KEY:latest'
      - '--set-secrets=GCS_BUCKET_NAME=GCS_BUCKET_NAME:latest'
      - '--set-secrets=CORS_ORIGINS=CORS_ORIGINS:latest'
      - '--set-secrets=TASK_SECRET_KEY=TASK_SECRET_KEY:latest'
      - '--set-secrets=GCP_PROJECT_ID=GCP_PROJECT_ID:latest'
    waitFor:
      - 'Run Migrations'

images:
  - 'europe-west1-docker.pkg.dev/fastdiet/fastdiet-repo/fastdiet-backend:latest'

availableSecrets:
  secretManager:
    - versionName: projects/fastdiet/secrets/INSTANCE_CONNECTION_NAME/versions/latest
      env: 'INSTANCE_CONNECTION_NAME'
    - versionName: projects/fastdiet/secrets/DB_USER/versions/latest
      env: 'DB_USER'
    - versionName: projects/fastdiet/secrets/DB_PASS/versions/latest
      env: 'DB_PASS'
    - versionName: projects/fastdiet/secrets/DB_NAME/versions/latest
      env: 'DB_NAME'