options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # 1️⃣ Construir la imagen de Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--platform=linux/amd64',
      '-t', 'europe-west1-docker.pkg.dev/fastdiet/fastdiet-repo/fastdiet-backend:latest',
      '.'
    ]

  # 2️⃣ Subir la imagen al Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'europe-west1-docker.pkg.dev/fastdiet/fastdiet-repo/fastdiet-backend:latest'
    ]

  # 3️⃣ Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fastdiet-backend-service'
      - '--image=europe-west1-docker.pkg.dev/fastdiet/fastdiet-repo/fastdiet-backend:latest'
      - '--platform=managed'
      - '--region=europe-west1'
      - '--allow-unauthenticated'
      - '--service-account=fastdiet-service-account@fastdiet.iam.gserviceaccount.com'
      - '--add-cloudsql-instances=fastdiet:europe-west1:fastdiet-db-instance'
      - '--set-secrets=INSTANCE_CONNECTION_NAME=INSTANCE_CONNECTION_NAME:latest'
      - '--set-secrets=DB_USER=DB_USER:latest'
      - '--set-secrets=DB_PASS=DB_PASS:latest'
      - '--set-secrets=DB_NAME=DB_NAME:latest'
      - '--set-secrets=JWT_SECRET_KEY=JWT_SECRET_KEY:latest'
      - '--set-secrets=JWT_ALGORITHM=JWT_ALGORITHM:latest'
      - '--set-secrets=SENDER_EMAIL=SENDER_EMAIL:latest'
      - '--set-secrets=BREVO_API_KEY=BREVO_API_KEY:latest'
      - '--set-secrets=WEB_CLIENT_ID=WEB_CLIENT_ID:latest'
      - '--set-secrets=SPOONACULAR_API_KEY=SPOONACULAR_API_KEY:latest'
      - '--set-secrets=GCS_BUCKET_NAME=GCS_BUCKET_NAME:latest'
      - '--set-secrets=CORS_ORIGINS=CORS_ORIGINS:latest'
      - '--set-secrets=TASK_SECRET_KEY=TASK_SECRET_KEY:latest'
      - '--set-secrets=GCP_PROJECT_ID=GCP_PROJECT_ID:latest'

# Opcional: especificar las imágenes creadas
images:
  - 'europe-west1-docker.pkg.dev/fastdiet/fastdiet-repo/fastdiet-backend:latest'
