"""Add table feedback

Revision ID: 118b259a5c85
Revises: 28e42b1da4bc
Create Date: 2025-10-12 14:12:38.594397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '118b259a5c85'
down_revision: Union[str, None] = '28e42b1da4bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.Enum('suggestion', 'bug', 'other', name='feedbacktype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('app_version', sa.String(length=50), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('platform_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('new', 'in_progress', 'resolved', 'wont_fix', name='feedbackstatus'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
