"""add scores

Revision ID: 1951d42bd83d
Revises: ca8bca042b3a
Create Date: 2025-10-25 11:28:54.680121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1951d42bd83d'
down_revision: Union[str, None] = 'ca8bca042b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('health_score', sa.Float(), nullable=True))
    op.add_column('recipes', sa.Column('spoonacular_score', sa.Float(), nullable=True))
    op.create_index(op.f('ix_recipes_health_score'), 'recipes', ['health_score'], unique=False)
    op.create_index(op.f('ix_recipes_spoonacular_score'), 'recipes', ['spoonacular_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_spoonacular_score'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_health_score'), table_name='recipes')
    op.drop_column('recipes', 'spoonacular_score')
    op.drop_column('recipes', 'health_score')
    # ### end Alembic commands ###
