"""Creator id in Recipe

Revision ID: 26753b985f93
Revises: 85d0f581475f
Create Date: 2025-07-13 20:55:19.126953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26753b985f93'
down_revision: Union[str, None] = '85d0f581475f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipes', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'creator_id')
    # ### end Alembic commands ###
