"""Add created_at to reset and verification codes

Revision ID: 28e42b1da4bc
Revises: 7d3726e661e1
Create Date: 2025-09-11 19:26:40.033114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '28e42b1da4bc'
down_revision: Union[str, None] = '7d3726e661e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verification_codes', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('password_reset_codes', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.alter_column('password_reset_codes', 'code',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('password_reset_codes', 'code',
               existing_type=sa.String(length=8),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('password_reset_codes', 'created_at')
    op.drop_column('email_verification_codes', 'created_at')
    # ### end Alembic commands ###
