"""Add translations of some fields of recipes

Revision ID: 2f802fbfabbc
Revises: e0a1ab8b501c
Create Date: 2025-08-12 11:35:01.538696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f802fbfabbc'
down_revision: Union[str, None] = 'e0a1ab8b501c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('title_es', sa.String(length=255), nullable=True))
    op.add_column('recipes', sa.Column('summary_es', sa.Text(), nullable=True))
    op.add_column('recipes', sa.Column('analyzed_instructions_es', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'analyzed_instructions_es')
    op.drop_column('recipes', 'summary_es')
    op.drop_column('recipes', 'title_es')
    # ### end Alembic commands ###
