"""Add goal to user preferences

Revision ID: 30c324efc3bb
Revises: 9fec4bbc68e0
Create Date: 2025-05-14 19:01:57.373676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c324efc3bb'
down_revision: Union[str, None] = '9fec4bbc68e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('goal', sa.Enum('lose_weight', 'maintain_weight', 'gain_weight', name='goal_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'goal')
    # ### end Alembic commands ###
