"""Add attributes of basic info

Revision ID: 3265514ac760
Revises: e7d74af6b2a1
Create Date: 2025-05-14 13:22:17.355950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3265514ac760'
down_revision: Union[str, None] = 'e7d74af6b2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('height', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'height')
    op.drop_column('users', 'weight')
    op.drop_column('users', 'age')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
