"""Update in recipes information

Revision ID: 3f5f83ab5b1d
Revises: 146d5cc10a9e
Create Date: 2025-06-10 17:40:18.197929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3f5f83ab5b1d'
down_revision: Union[str, None] = '146d5cc10a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instructions_equipments')
    op.drop_table('instructions')
    op.drop_table('equipments')
    op.add_column('recipes', sa.Column('analyzed_instructions', sa.JSON(), nullable=True))
    op.alter_column('recipes', 'summary',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('recipes', 'price_per_serving')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('price_per_serving', mysql.FLOAT(), nullable=True))
    op.alter_column('recipes', 'summary',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('recipes', 'analyzed_instructions')
    op.create_table('instructions_equipments',
    sa.Column('instruction_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('equipment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], name='instructions_equipments_ibfk_1'),
    sa.ForeignKeyConstraint(['instruction_id'], ['instructions.id'], name='instructions_equipments_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instruction_id', 'equipment_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('equipments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('image_url', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('instructions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('step_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('step_text', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('recipe_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='instructions_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
