"""Translations and possible units added to Ingredients table

Revision ID: 5fa3318c04d8
Revises: 26753b985f93
Create Date: 2025-08-05 12:36:59.107246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5fa3318c04d8'
down_revision: Union[str, None] = '26753b985f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('name_en', sa.String(length=255), nullable=False))
    op.add_column('ingredients', sa.Column('name_es', sa.String(length=255), nullable=True))
    op.add_column('ingredients', sa.Column('possible_units_en', sa.JSON(), nullable=True))
    op.add_column('ingredients', sa.Column('possible_units_es', sa.JSON(), nullable=True))
    op.drop_index('ix_ingredients_name', table_name='ingredients')
    op.create_index(op.f('ix_ingredients_name_en'), 'ingredients', ['name_en'], unique=True)
    op.create_index(op.f('ix_ingredients_name_es'), 'ingredients', ['name_es'], unique=False)
    op.drop_column('ingredients', 'name')
    op.alter_column('recipes', 'summary',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'summary',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.add_column('ingredients', sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.drop_index(op.f('ix_ingredients_name_es'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_name_en'), table_name='ingredients')
    op.create_index('ix_ingredients_name', 'ingredients', ['name'], unique=True)
    op.drop_column('ingredients', 'possible_units_es')
    op.drop_column('ingredients', 'possible_units_en')
    op.drop_column('ingredients', 'name_es')
    op.drop_column('ingredients', 'name_en')
    # ### end Alembic commands ###
