"""Ingredients in recipes

Revision ID: 6a1041945ca4
Revises: 3f5f83ab5b1d
Create Date: 2025-06-10 21:51:29.561028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6a1041945ca4'
down_revision: Union[str, None] = '3f5f83ab5b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes_ingredients',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('original_ingredient_name', sa.String(length=512), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('measures_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'ingredient_id')
    )
    op.add_column('ingredients', sa.Column('spoonacular_id', sa.Integer(), nullable=True))
    op.add_column('ingredients', sa.Column('image_filename', sa.String(length=255), nullable=True))
    op.add_column('ingredients', sa.Column('aisle', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=False)
    op.create_index(op.f('ix_ingredients_spoonacular_id'), 'ingredients', ['spoonacular_id'], unique=True)
    op.drop_column('ingredients', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('image_url', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_ingredients_spoonacular_id'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.drop_column('ingredients', 'aisle')
    op.drop_column('ingredients', 'image_filename')
    op.drop_column('ingredients', 'spoonacular_id')
    op.drop_table('recipes_ingredients')
    # ### end Alembic commands ###
