"""Recipe delete on cascade

Revision ID: 7d3726e661e1
Revises: 2f802fbfabbc
Create Date: 2025-08-31 15:51:45.056865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d3726e661e1'
down_revision: Union[str, None] = '2f802fbfabbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('recipes_ibfk_1'), 'recipes', type_='foreignkey')
    op.create_foreign_key(None, 'recipes', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.create_foreign_key(op.f('recipes_ibfk_1'), 'recipes', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###
