"""Added calories to recipe

Revision ID: 85d0f581475f
Revises: 6a1041945ca4
Create Date: 2025-07-01 10:19:04.104924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d0f581475f'
down_revision: Union[str, None] = '6a1041945ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingredients_name', table_name='ingredients')
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=True)
    op.add_column('recipes', sa.Column('calories', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'calories')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.create_index('ix_ingredients_name', 'ingredients', ['name'], unique=False)
    # ### end Alembic commands ###
