"""Add activity_level to user_preferences

Revision ID: 9fec4bbc68e0
Revises: 3265514ac760
Create Date: 2025-05-14 18:05:54.577491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9fec4bbc68e0'
down_revision: Union[str, None] = '3265514ac760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('activity_level', sa.Enum('sedentary', 'light', 'moderate', 'high', 'very_high', name='activity_level_enum'), nullable=True))
    op.drop_column('user_preferences', 'very_healthy')
    op.drop_column('user_preferences', 'cheap')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('cheap', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('user_preferences', sa.Column('very_healthy', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('user_preferences', 'activity_level')
    # ### end Alembic commands ###
