"""Created at for the recipe

Revision ID: ca8bca042b3a
Revises: 118b259a5c85
Create Date: 2025-10-21 21:15:59.558913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca8bca042b3a'
down_revision: Union[str, None] = '118b259a5c85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('recipes', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'updated_at')
    op.drop_column('recipes', 'created_at')
    # ### end Alembic commands ###
