"""Add meal type to meal items table

Revision ID: e0a1ab8b501c
Revises: 5fa3318c04d8
Create Date: 2025-08-11 18:04:41.924595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0a1ab8b501c'
down_revision: Union[str, None] = '5fa3318c04d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_items', sa.Column('meal_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_items', 'meal_type')
    # ### end Alembic commands ###
