from enum import StrEnum

class ErrorCode(StrEnum):
    # User & Auth
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS"
    USER_ALREADY_VERIFIED = "USER_ALREADY_VERIFIED"
    EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
    EMAIL_ALREADY_VERIFIED = "EMAIL_ALREADY_VERIFIED"
    EMAIL_NOT_VALID = "EMAIL_NOT_VALID"
    EMAIL_SEND_ERROR = "EMAIL_SEND_ERROR"
    USER_NOT_VERIFIED = "USER_NOT_VERIFIED"
    USER_NOT_VERIFIED_FOR_RESET = "USER_NOT_VERIFIED_FOR_RESET"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_TOKEN = "INVALID_TOKEN"
    INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN"
    INVALID_EMAIL_VERIFICATION_CODE = "INVALID_EMAIL_VERIFICATION_CODE"
    INVALID_RESET_CODE = "INVALID_RESET_CODE"
    INVALID_OR_EXPIRED_REFRESH_TOKEN = "INVALID_OR_EXPIRED_REFRESH_TOKEN"
    INVALID_GOOGLE_TOKEN = "INVALID_GOOGLE_TOKEN"
    INVALID_APPLE_TOKEN = "INVALID_APPLE_TOKEN"

    # Recipe & Meal
    RECIPE_NOT_FOUND = "RECIPE_NOT_FOUND"
    RECIPE_ACCESS_DENIED = "RECIPE_ACCESS_DENIED"
    IMPORTED_RECIPE_DELETE_FORBIDDEN = "IMPORTED_RECIPE_DELETE_FORBIDDEN"
    FORBIDDEN_RECIPE_DELETE = "FORBIDDEN_RECIPE_DELETE"
    RECIPE_LINKED_TO_MEAL_PLAN = "RECIPE_LINKED_TO_MEAL_PLAN"
    DUPLICATED_INGREDIENT = "DUPLICATED_INGREDIENT"
    CANNOT_DELETE_IMPORTED_RECIPE = "CANNOT_DELETE_IMPORTED_RECIPE"
    FORBIDDEN_RECIPE_UPDATE = "FORBIDDEN_RECIPE_UPDATE"
    IMPORTED_RECIPE_UPDATE_FORBIDDEN = "IMPORTED_RECIPE_UPDATE_FORBIDDEN"
    MEAL_ITEM_NOT_FOUND = "MEAL_ITEM_NOT_FOUND"
    MEAL_ITEM_ACCESS_DENIED = "MEAL_ITEM_ACCESS_DENIED"
    MEAL_PLAN_ACCESS_DENIED = "MEAL_PLAN_ACCESS_DENIED"
    MEAL_PLAN_NOT_FOUND = "MEAL_PLAN_NOT_FOUND"
    MEAL_PLAN_GENERATION_FAILED = "MEAL_PLAN_GENERATION_FAILED"
    USER_PREFERENCES_NOT_FOUND = "USER_PREFERENCES_NOT_FOUND"


    # Preferences
    CUISINE_REGIONS_NOT_FOUND = "CUISINE_REGIONS_NOT_FOUND"
    INTOLERANCES_NOT_FOUND = "INTOLERANCES_NOT_FOUND"
    DIET_TYPE_NOT_FOUND = "DIET_TYPE_NOT_FOUND"
    DISH_TYPE_NOT_FOUND = "DISH_TYPE_NOT_FOUND"
    DUPLICATED_DISH_TYPE = "DUPLICATED_DISH_TYPE"
    PREFERENCES_TOO_STRICT = "PREFERENCES_TOO_STRICT"

    # Generic
    INCORRECT_CURRENT_PASSWORD = "INCORRECT_CURRENT_PASSWORD"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
